# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b4f5d9ce-39f5-4637-a7f9-2f19a99e8c86";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/b4f5d9ce-39f5-4637-a7f9-2f19a99e8c86";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/13F2-3133";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  services.pipewire.extraConfig.pipewire-pulse."99-custom.conf" = {
    "pulse.cmd" = [
      {
        cmd = "load-module";
        args = "module-null-sink sink_name=virtual_sink sink_properties=device.description=\"Virtual_Stereo\"";
        flags = [ ];
      }
      {
        cmd = "load-module";
        args = "module-loopback source=virtual_sink.monitor sink=alsa_output.pci-0000_07_00.6.analog-stereo";
        flags = [ ];
      }
      {
        cmd = "load-module";
        args = "module-remap-source master=alsa_input.pci-0000_07_00.6.analog-stereo source_name=MICROPHONE source_properties=device.description=MICROPHONE";
        flags = [ ];
      }
    ];
  };

  systemd.tpm2.enable = false;
  boot.initrd.systemd.tpm2.enable = false;
}
